### ISSUE TITLE
[Crash] MissingLibraryException: librealm-jni.so

### ISSUE THREAD

**Issue by ConstantinKV** [saltedge/sca-authenticator-android#219]
Сведения о сеансе: 3.0.0 (44);  8.1.0; Nexus 5X  

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.saltedge.authenticator/com.saltedge.authenticator.features.launcher.LauncherActivity}: java.lang.RuntimeException: Failed to call observer method
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
```
  
```
Caused by com.getkeepsafe.relinker.MissingLibraryException: librealm-jni.so
       at com.getkeepsafe.relinker.a.a(ApkLibraryInstaller.java:123)
       at com.getkeepsafe.relinker.c.c(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.c.a(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.b.a(ReLinker.java:70)
       at com.getkeepsafe.relinker.b.a(ReLinker.java:57)
       at io.realm.internal.l.a(RealmCore.java:60)
       at io.realm.q.a(Realm.java:322)
       at io.realm.q.a(Realm.java:265)
       at com.saltedge.authenticator.models.a.c.a(RealmManager.kt:43)
       at com.saltedge.authenticator.features.launcher.LauncherViewModel.onLifeCycleResume(LauncherViewModel.kt:56)
       at java.lang.reflect.Method.invoke(Method.java)
       at androidx.lifecycle.a$b.a(ClassesInfoCache.java:216)
       at androidx.lifecycle.a$a.a(ClassesInfoCache.java:194)
       at androidx.lifecycle.a$a.a(ClassesInfoCache.java:185)
       at androidx.lifecycle.ReflectiveGenericLifecycleObserver.a(ReflectiveGenericLifecycleObserver.java:37)
       at androidx.lifecycle.n$a.a(LifecycleRegistry.java:361)
       at androidx.lifecycle.n.a(LifecycleRegistry.java:300)
       at androidx.lifecycle.n.d(LifecycleRegistry.java:339)
       at androidx.lifecycle.n.c(LifecycleRegistry.java:145)
       at androidx.lifecycle.n.a(LifecycleRegistry.java:131)
       at androidx.lifecycle.v.a(ReportFragment.java:68)
       at androidx.lifecycle.v.a(ReportFragment.java:144)
       at androidx.lifecycle.v.onStart(ReportFragment.java:109)
       at android.app.Fragment.performStart(Fragment.java:2534)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1315)
       at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618)
       at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3027)
       at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2984)
       at android.app.FragmentController.dispatchStart(FragmentController.java:189)
       at android.app.Activity.performStart(Activity.java:7035)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by ConstantinKV** [comment]
https://github.com/realm/realm-java/issues/6798  
https://github.com/realm/realm-java/issues/6727
