### ISSUE TITLE
[Crash] RuntimeException: Fail to connect to camera service

### ISSUE THREAD

**Issue by ConstantinKV** [saltedge/sca-authenticator-android#258]
```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=328, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.saltedge.authenticator/com.saltedge.authenticator.features.qr.QrScannerActivity}: java.lang.RuntimeException: Fail to connect to camera service
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5360)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5401)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8154)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

```
Caused by java.lang.RuntimeException: Fail to connect to camera service
       at android.hardware.Camera.<init>(Camera.java:551)
       at android.hardware.Camera.open(Camera.java:396)
       at com.google.android.gms.vision.a.c(com.google.android.gms:play-services-vision-common@@19.1.0:82)
       at com.google.android.gms.vision.a.a(com.google.android.gms:play-services-vision-common@@19.1.0:22)
       at com.saltedge.authenticator.features.qr.QrScannerActivity.B(QrScannerActivity.kt:186)
       at com.saltedge.authenticator.features.qr.QrScannerActivity.onRequestPermissionsResult(QrScannerActivity.kt:85)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8482)
       at android.app.Activity.dispatchActivityResult(Activity.java:8304)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5353)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5401)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8154)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by ConstantinKV** [comment]
```
Fatal Exception: java.lang.RuntimeException: Fail to connect to camera service
       at android.hardware.Camera.<init>(Camera.java:545)
       at android.hardware.Camera.open(Camera.java:385)
       at com.google.android.gms.vision.CameraSource.zzc(CameraSource.java:82)
       at com.google.android.gms.vision.CameraSource.start(CameraSource.java:22)
       at com.saltedge.authenticator.features.qr.QrScannerActivity.startCameraSource(QrScannerActivity.java:174)
       at com.saltedge.authenticator.features.qr.QrScannerActivity.access$startCameraSource(QrScannerActivity.java:54)
       at com.saltedge.authenticator.features.qr.QrScannerActivity$setupSurface$1.surfaceCreated(QrScannerActivity.java:142)
       at android.view.SurfaceView.updateWindow(SurfaceView.java:666)
       at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:199)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:921)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1230)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6731)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:560)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6117)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```
