### ISSUE TITLE
[Crash] NullPointerException: createProgressDialog

### ISSUE THREAD

**Issue by ConstantinKV** [saltedge/sca-authenticator-android#261]
App version: 3.2.0 (49)  
Android version: 10  
Device version: realme 5pro  
  
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
       at android.app.Dialog.<init>(Dialog.java:196)
       at android.app.ColorBaseAlertDialog.<init>(ColorBaseAlertDialog.java:33)
       at android.app.AlertDialog.<init>(AlertDialog.java:208)
       at android.app.AlertDialog.<init>(AlertDialog.java:204)
       at android.app.ProgressDialog.<init>(ProgressDialog.java:112)
       at com.saltedge.authenticator.widget.fragment.BaseFragment.createProgressDialog(BaseFragment.java:46)
       at com.saltedge.authenticator.widget.fragment.BaseFragment.showLoadProgress(BaseFragment.java:41)
       at com.saltedge.authenticator.widget.fragment.WebViewFragment$webViewClient$1.onPageStarted(WebViewFragment.java:69)
       at i6.c(i6.java:2)
       at Hn.handleMessage(Hn.java:145)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:228)
       at android.app.ActivityThread.main(ActivityThread.java:7782)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
```

**Comment by ConstantinKV** [comment]
solved
