### ISSUE TITLE
[Crash] InvalidKeyException: Keystore operation failed

### ISSUE THREAD

**Issue by ConstantinKV** [saltedge/sca-authenticator-android#269]
3.2.0 (49)  
 6.0.1  
 Galaxy Note4  

```
Caused by java.security.InvalidKeyException: Keystore operation failed
       at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1000)
       at android.security.KeyStore.getInvalidKeyException(KeyStore.java:1020)
       at android.security.keystore.KeyStoreCryptoOperationUtils.getInvalidKeyExceptionForInit(KeyStoreCryptoOperationUtils.java:53)
       at android.security.keystore.AndroidKeyStoreSignatureSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreSignatureSpiBase.java:219)
       at android.security.keystore.AndroidKeyStoreSignatureSpiBase.engineInitSign(AndroidKeyStoreSignatureSpiBase.java:99)
       at android.security.keystore.AndroidKeyStoreSignatureSpiBase.engineInitSign(AndroidKeyStoreSignatureSpiBase.java:77)
       at java.security.Signature$SignatureImpl.engineInitSign(Signature.java:706)
       at java.security.Signature.initSign(Signature.java:357)
       at com.saltedge.authenticator.sdk.tools.sign.SignatureToolsKt.signWith(SignatureToolsKt.java:44)
       at com.saltedge.authenticator.sdk.tools.sign.SignatureToolsKt.createSignatureHeader(SignatureToolsKt.java:37)
       at com.saltedge.authenticator.sdk.network.connector.ConnectorToolsKt.createSignedRequestData(ConnectorToolsKt.java:84)
       at com.saltedge.authenticator.sdk.network.connector.ConnectorToolsKt.createSignedRequestData(ConnectorToolsKt.java:50)
       at com.saltedge.authenticator.sdk.network.connector.ConnectorToolsKt.createSignedRequestData$default(ConnectorToolsKt.java:44)
       at com.saltedge.authenticator.sdk.network.connector.ConsentsConnector.fetchConsents(ConsentsConnector.java:55)
       at com.saltedge.authenticator.sdk.AuthenticatorApiManager.getConsents(AuthenticatorApiManager.java:238)
       at com.saltedge.authenticator.features.connections.list.ConnectionsListViewModel.refreshConsents(ConnectionsListViewModel.java:216)
       at com.saltedge.authenticator.features.connections.list.ConnectionsListViewModel.onStart(ConnectionsListViewModel.java:94)
```

**Comment by whodonotknowme** [comment]
do you solve this problem?

**Comment by ConstantinKV** [comment]
@whodonotknowme yes, we have solved it. If the issue appeared again please provide phone config and backtrace if possible, or env description.
